### ISSUE TITLE
Fails with "must implement .build() function"

### ISSUE THREAD

**Issue by BryanCrotaz** [chadhietala/broccoli-rollup#16]
Using "broccoli-rollup": "^1.0.3",
```
import Rollup from 'broccoli-rollup';
...
// bundle = es6->es5 (this works)
// now the bit that doesn't
bundle = new Rollup([bundle], {
	rollup: {
		entry: 'index.js',
		dest: 'index.js'
	}
});
```
```
Build failed.

Error: Plugin subclasses must implement a .build() function
  at Plugin.build (C:\projects\sc-pp\sc-pp-backend\node_modules\broccoli-plugin\index.js:101:9)
  at C:\projects\sc-pp\sc-pp-backend\node_modules\broccoli-plugin\read_compat.js:61:34
  at tryCatch (C:\projects\sc-pp\sc-pp-backend\node_modules\rsvp\dist\rsvp.js:538:12)
  at invokeCallback (C:\projects\sc-pp\sc-pp-backend\node_modules\rsvp\dist\rsvp.js:553:13)
  at publish (C:\projects\sc-pp\sc-pp-backend\node_modules\rsvp\dist\rsvp.js:521:7)
  at flush (C:\projects\sc-pp\sc-pp-backend\node_modules\rsvp\dist\rsvp.js:2373:5)
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

**Comment by BryanCrotaz** [comment]
Sorry, typo on my side.
